name: CI
on:
  push:
    branches:
      - "fabio"
      - "Clebson"
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/Checkout@v3

      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirement.txt

      - name: Run test
        run: |
          python3 tests.py

      - name: Push docker hub
        if: success()
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        if: success()
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: fabiojssf/desafiodevops
      
      - name: Build and push
        if: success()
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: fabiojssf/desafiodevops:latest
          context: .