name: CI
on:
  push:
    branches:
      - "fabio"
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/Checkout@v3

      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirement.txt

      - name: Run test
        run: |
          python3 tests.py