name: Testa a compatibilidade com versões do Phython
on:
  push:
    branches:
      - "fabio"
jobs:
  unittest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ '3.5.10', '3.6.7', '3.7.1', '3.8.2', '3.9.0' ]
    steps:
      - name: Checkout Project
        uses: actions/Checkout@v3

      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirement.txt

      - name: Run test
        run: |
          python3 tests.py